name: Create MacOS Bundle (arm64)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: recursive

    - name: Install Homebrew deps
      run: |
        brew update
        brew install cmake qt qcoro6 kirigami extra-cmake-modules p7zip

    - name: Install additional tools
      run: |
        brew install --cask android-commandlinetools || true
        brew install android-platform-tools || true
        brew install openjdk || true

    - name: Set Qt env
      run: |
        echo "Qt path:"
        brew --prefix qt
        export CMAKE_PREFIX_PATH="$(brew --prefix qt)"

    - name: Build MacOS app (official script)
      run: |
        cd macOs
        chmod +x buildMacOs.sh
        ./buildMacOs.sh --open

    - name: Find DMG
      run: |
        find macOs -name "*.dmg"

    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: macOs/*.dmg
        tag: ${{ github.event.release.tag_name }}
        overwrite: true
