name: Build MacOS (arm64)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Install dependencies
      run: |
        brew update
        brew install cmake qt qcoro6 extra-cmake-modules p7zip

    - name: Set Qt environment
      run: |
        echo "Qt prefix: $(brew --prefix qt)"
        export CMAKE_PREFIX_PATH="$(brew --prefix qt)"

    - name: Build project
      run: |
        cd macOs
        chmod +x buildMacOs.sh
        ./buildMacOs.sh

    - name: Upload DMG
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: macOs/build_*/QRookie*.dmg
        tag: ${{ github.ref_name }}
        overwrite: true
